# Generated by Django 3.1.2 on 2020-11-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionperiod',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user'),
            preserve_default=False,
        ),
    ]
