# Generated by Django 3.1.2 on 2020-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionperiod',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
