# Generated by Django 3.1.2 on 2020-11-03 12:51

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'username already taken'}, max_length=250, unique=True, validators=[users.validators.UsernameValidator()])),
                ('email', models.EmailField(error_messages={'unique': 'email already exist'}, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('enduser', 'enduser')], default='superadmin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user',
            },
        ),
    ]
