# Generated by Django 3.1.2 on 2020-11-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction_period', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Bank', 'Bank'), ('Digital Wallet', 'Digital Wallet'), ('Cash', 'Cash')], default='Bank', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'money_account',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneys_account', to='money.account')),
                ('transaction_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneys_transaction_period', to='transaction_period.transactionperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneys_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'money_money',
            },
        ),
    ]
