# Generated by Django 3.1.2 on 2020-11-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_period', '0002_transactionperiod_user'),
        ('money', '0002_auto_20201031_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='transaction_period',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='moneys_transaction_period', to='transaction_period.transactionperiod'),
            preserve_default=False,
        ),
    ]
