# Generated by Django 3.1.2 on 2020-11-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_period', '0001_initial'),
        ('money', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income_expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('expense_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='money.account')),
                ('transaction_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_transaction_period', to='transaction_period.transactionperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_expense_expense',
            },
        ),
    ]
